apiVersion: v1
kind: Service
metadata:
  name: volontario-gateway
  labels:
    app.kubernetes.io/name: volontario
    app.kubernetes.io/component: volontario-gateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: volontario-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
