apiVersion: v1
kind: Service
metadata:
  name: volontario-minio
  labels:
    app.kubernetes.io/component: volontario-minio
    app.kubernetes.io/name: volontario
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: volontario-minio
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: tcp-9000
    - protocol: TCP
      port: 9001
      targetPort: 9001
      name: tcp-9001
