apiVersion: apps/v1
kind: Deployment
metadata:
  name: volontario-back
  labels:
    app.kubernetes.io/component: volontario-back
    app.kubernetes.io/name: volontario
{{ toYaml .Values.volontarioBack.podLabels | indent 4 }}
  annotations:
{{ toYaml .Values.volontarioBack.podAnnotations | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: volontario-back
  template:
    metadata:
      labels:
        app.kubernetes.io/component: volontario-back
        app.kubernetes.io/name: volontario
    spec:
      containers:
      - name: volontario-back
        image: {{ .Values.volontarioBack.image.repository }}:{{ .Values.volontarioBack.image.tag }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        imagePullPolicy: {{ .Values.volontarioBack.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: volontario-back-secret
        - configMapRef:
            name: volontario-back-cm
