apiVersion: v1
kind: Service
metadata:
  name: volontario-db
  labels:
    app.kubernetes.io/component: volontario-db
    app.kubernetes.io/name: volontario
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: volontario-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
