apiVersion: v1
kind: Secret
metadata:
  name: volontario-minio-secret
  labels:
    app.kubernetes.io/component: volontario-minio
    app.kubernetes.io/name: volontario
type: Opaque
data:
  MINIO_ROOT_USER: {{ .Values.env.minioUsername | b64enc }}
  MINIO_ROOT_PASSWORD: {{ .Values.env.minioPassword | b64enc }}
