apiVersion: v1
kind: Service
metadata:
  name: volontario-front
  labels:
    app.kubernetes.io/component: volontario-front
    app.kubernetes.io/name: volontario
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: volontario-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
