apiVersion: v1
kind: Secret
metadata:
  name: volontario-back-secret
  labels:
    app.kubernetes.io/component: volontario-back
    app.kubernetes.io/name: volontario
type: Opaque
data:
  POSTGRES_USER: {{ .Values.env.dbUsername | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.env.dbPassword | b64enc }}
  MINIO_ROOT_USER:  {{ .Values.env.minioUsername | b64enc }}
  MINIO_ROOT_PASSWORD: {{ .Values.env.minioPassword | b64enc }}
  MAILSERVER_USERNAME: {{ .Values.env.mailserverUsername | b64enc }}
  MAILSERVER_PASSWORD: {{ .Values.env.mailserverPassword | b64enc }}