apiVersion: v1
kind: Service
metadata:
  name: volontario-back
  labels:
    app.kubernetes.io/component: volontario-back
    app.kubernetes.io/name: volontario
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: volontario-back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
