apiVersion: v1
kind: Secret
metadata:
  name: volontario-db-secret
  labels:
    app.kubernetes.io/component: volontario-db
    app.kubernetes.io/name: volontario
type: Opaque
data:
  POSTGRES_USER: {{ .Values.env.dbUsername | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.env.dbPassword | b64enc }}
