# playbook for Ubuntu 22 LTS

---
- hosts: all
  remote_user: root
  tasks:
    - name: Install docker packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
    - name: Add Docker s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Set up the stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present
        update_cache: yes
    - name: Install docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes
    - name: Install docker-compose
      get_url: 
        url : https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
    - name: Install certbot
      apt:
        name: certbot
        state: present
        update_cache: yes