version: '3'
services:
  volontario-back:
    image: volontario-back:latest
    restart: always
    depends_on:
      - volontario-db
    build:
      context: ../volontario.server
    ports:
      - '8080:8080'
    env_file: '.env'
  volontario-db:
    image: postgres:15.2-alpine
    restart: always
    env_file: '.env'
    volumes:
      - volontario-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  volontario-db:
