version: '3'
services:
  volontario-gateway:
    image: nginx:1.25-alpine
    restart: always
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    environment:
      - VOLONTARIO_DOMAIN=localhost # change to 'volontario.me' for production
    ports:
      - '80:80'
      # https to be configured once we get new environment
      # - '443:443' 
  volontario-front:
    image: volontario-front:latest
    restart: always
    depends_on:
      - volontario-back
    build:
      context: ../volontario.client/volontario.client.application/volontario
      args:
        CLIENT_ENVIRONMENT: localdev # change to 'production' when deploying to prod
  volontario-back:
    image: volontario-back:latest
    restart: always
    depends_on:
      - volontario-db
      - volontario-mailserver
    build:
      context: ../volontario.server
    env_file: '.env'
  volontario-db:
    image: postgres:15.4-alpine
    restart: always
    env_file: '.env'
    volumes: 
      - volontario-db:/var/lib/postgresql/data
  volontario-minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-storage:/data
    env_file: '.env'
    command: server --console-address ":9001" /data

  wordpress:
    depends_on: 
      - wordpress-db
    image: wordpress:php8.0
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=wordpress-db:3306
      - WORDPRESS_DB_USER=admin
      - WORDPRESS_DB_PASSWORD=admin
      - WORDPRESS_DB_NAME=wordpress
  wordpress-db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes: 
      - dbdata:/var/lib/mysql

volumes:
  volontario-db:
  wordpress-db:
  minio-storage:
