version: '3'
services:
  volontario-front:
    image: volontario-front:latest
    restart: always
    depends_on:
      - volontario-back
    ports:
      - '8000:80' # should be 80:80 on production
    build:
      context: ../volontario.client/volontario.client.application/volontario
    environment:
      - BACKEND_HOSTNAME=volontario-back
  volontario-back:
    image: volontario-back:latest
    restart: always
    depends_on:
      - volontario-db
      - volontario-mailserver
    ports:
      - '8080:8080'
    build:
      context: ../volontario.server
    env_file: 'variables.env'
    environment:
      - MAILSERVER_HOSTNAME=volontario-mailserver
      - MAILSERVER_PORT=25 # for now, maybe we'll introduce TLS and then port will change
  volontario-db:
    image: postgres:15.2-alpine
    restart: always
    env_file: 'variables.env'
    volumes: 
      - volontario-db:/var/lib/postgresql/data
  volontario-mailserver:
    image: mwader/postfix-relay:1.1
    restart: always
    hostname: volontario.me # placeholder domain, to be changed later
volumes:
  volontario-db:
    driver: local

# to-do maybe another nginx as proxy? (although reverse proxy would be better running on another machine)