version: '3'
services:
  db:
    image: postgres:15.4-alpine
    restart: always
    env_file: '.env'
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  volontario-minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-storage:/data
    env_file: '.env'
    command: server --console-address ":9001" /data
volumes:
  db:
  minio-storage: