version: '3'
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  volontario-mailserver:
    image: mwader/postfix-relay:1.1
    restart: always
    environment:
      - POSTFIX_myhostname=smtp.domain.tld
      - OPENDKIM_DOMAINS=smtp.domain.tld
    ports:
      - '25:25'
    hostname: volontario.me # placeholder domain, to be changed later
volumes:
  db:
    driver: local