version: '3'
name: volontario
services:
  volontario-front:
    image: volontario-front:latest
    restart: always
    build:
      context: ../volontario.client/volontario.client.application/volontario
      args:
        CLIENT_ENVIRONMENT: ${CLIENT_ENVIRONMENT:-localdev8080}
    ports:
      - '4200:80'
  volontario-db:
    image: postgres:16.1-alpine
    restart: always
    env_file: '.env'
    volumes:
      - volontario-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  volontario-minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-storage:/data
    env_file: '.env'
    command: server --console-address ":9001" /data
volumes:
  volontario-db:
  minio-storage:
