version: '3'
services:
  volontario-back:
    image: volontario-back:latest
    restart: always
    depends_on:
      - volontario-db
      - volontario-mailserver
    build:
      context: ../volontario.server
    ports:
      - '8080:8080'
    env_file: 'variables.env'
  volontario-db:
    image: postgres:15.2-alpine
    restart: always
    env_file: 'variables.env'
    volumes:
      - volontario-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  volontario-mailserver:
    image: mwader/postfix-relay:1.1
    restart: always
    environment:
      - POSTFIX_myhostname=smtp.domain.tld
      - OPENDKIM_DOMAINS=smtp.domain.tld
    ports:
      - '25:25'
    hostname: volontario.me # placeholder domain, to be changed later
volumes:
  volontario-db:
    driver: local
