version: '3'
services:
  volontario-gateway:
    image: nginx:1.23-alpine
    restart: always
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    environment:
      - VOLONTARIO_DOMAIN=localhost # change to 'volontario.me' for production
    ports:
      - '80:80'
      # https to be configured once we get new environment
      # - '443:443' 
  volontario-front:
    image: volontario-front:latest
    restart: always
    depends_on:
      - volontario-back
    build:
      context: ../volontario.client/volontario.client.application/volontario
      args:
        CLIENT_ENVIRONMENT: localdev # change to 'production' when deploying to prod
  volontario-back:
    image: volontario-back:latest
    restart: always
    depends_on:
      - volontario-db
    build:
      context: ../volontario.server
    env_file: '.env'
  volontario-db:
    image: postgres:15.2-alpine
    restart: always
    env_file: '.env'
    volumes: 
      - volontario-db:/var/lib/postgresql/data
volumes:
  volontario-db: