version: '3'
services:
  volontario-gateway:
    image: nginx:1.23-alpine
    restart: always
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    environment:
      - VOLONTARIO_DOMAIN=localhost
    ports:
      - '80:80'
      # https to be configured once we get new environment
      # - '443:443' 
  volontario-front:
    image: volontario-front:latest
    restart: always
    depends_on:
      - volontario-back
    build:
      context: ../volontario.client/volontario.client.application/volontario
  volontario-back:
    image: volontario-back:latest
    restart: always
    depends_on:
      - volontario-db
      - volontario-mailserver
    build:
      context: ../volontario.server
    env_file: 'variables.env'
  volontario-db:
    image: postgres:15.2-alpine
    restart: always
    env_file: 'variables.env'
    volumes: 
      - volontario-db:/var/lib/postgresql/data
  volontario-mailserver:
    image: mwader/postfix-relay:1.1
    restart: always
    environment:
      - POSTFIX_myhostname=smtp.domain.tld
      - OPENDKIM_DOMAINS=smtp.domain.tld
    hostname: volontario.me # placeholder domain, to be changed later
volumes:
  volontario-db:
    driver: local