version: '3'
name: volontario
services:
  volontario-gateway:
    image: nginx:1.25-alpine
    restart: always
    volumes:
      - ./nginx/templates/${NGINX_CONFIG_TEMPLATE}:/etc/nginx/templates/default.conf.template
      - ${NGINX_CERT_PATH}:/etc/letsencrypt
    environment:
      - VOLONTARIO_DOMAIN=${VOLONTARIO_DOMAIN}
    ports:
      - '80:80'
      - '443:443'
      - '9001:9001'
  volontario-front:
    image: volontario-front:latest
    restart: always
    depends_on:
      - volontario-back
    build:
      context: ../volontario.client/volontario.client.application/volontario
      args:
        CLIENT_ENVIRONMENT: ${CLIENT_ENVIRONMENT:-localdev}
  volontario-back:
    image: volontario-back:latest
    restart: always
    depends_on:
      - volontario-db
    build:
      context: ../volontario.server
    env_file: '.env'
  volontario-db:
    image: postgres:16.1-alpine
    restart: always
    env_file: '.env'
    volumes: 
      - volontario-db:/var/lib/postgresql/data
      - ${POSTGRES_BACKUP_DIR}:/var/volontariodumps
  volontario-minio:
    image: minio/minio
    environment:
      - MINIO_SERVER_URL=${SCHEMA}://${VOLONTARIO_DOMAIN}:9001
      - MINIO_BROWSER_REDIRECT_URL=${SCHEMA}://${VOLONTARIO_DOMAIN}:9001/minio/ui
    volumes:
      - minio-storage:/data
    env_file: '.env'
    command: server --console-address ":9001" /data
volumes:
  volontario-db:
  minio-storage:
