version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    ports:
      - 50000:50000
    user: root
    restart: always
    privileged: true
    volumes:
      - /root/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  nginx:
    image: nginx:1.25-alpine
    restart: always
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - '80:80'
